# Generated by Django 3.0.11 on 2020-11-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201102_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='guardian',
        ),
    ]
