# Generated by Django 3.0.11 on 2020-11-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_contact_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='dob',
        ),
        migrations.AddField(
            model_name='guardian',
            name='client',
            field=models.ManyToManyField(related_name='client', to='base.Contact'),
        ),
    ]
