# Generated by Django 3.0.11 on 2020-11-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201103_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='client',
        ),
        migrations.AddField(
            model_name='guardian',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Contact'),
        ),
    ]
